### ISSUE TITLE
Electron Example: TypeError: Cannot read property 'invoke' of undefined

### ISSUE THREAD

**Issue by burgil** [mozilla/DeepSpeech-examples#145]
![image](https://user-images.githubusercontent.com/41600149/128582175-a0105add-d889-4ecb-9797-aea7b96f1b15.png)
---------------------------------------------
### Command Prompt Log:
```
> deepspeech-electron@1.0.0 dev-win D:\ds
> concurrently "npm start" "wait-on http://localhost:3000 && electron --inspect=5858 ."
[0]
[0] > deepspeech-electron@1.0.0 start D:\ds
[0] > react-scripts start
[0]
[0] i ｢wds｣: Project is running at http://10.100.102.47/
[0] i ｢wds｣: webpack output is served from
[0] i ｢wds｣: Content not from webpack is served from D:\ds\public
[0] i ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0]
[0] Compiled successfully!
[0]
[0] You can now view deepspeech-electron in the browser.
[0]
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://10.100.102.47:3000
[0]
[0] Note that the development build is not optimized.
[0] To create a production build, use npm run build.
[0]
[1]
[1] Debugger listening on ws://127.0.0.1:5858/0edf582c-320d-4c78-8f89-2f52b4762fa7
[1] For help, see: https://nodejs.org/en/docs/inspector
[1] TensorFlow: v2.3.0-6-g23ad988fcd
[1] DeepSpeech: v0.9.3-0-gf2e9c858
[1] model loaded
[0]
[0] Could not open react-dom.development.js in the editor.
[0]
[0] To set up the editor integration, add something like REACT_EDITOR=atom to the .env.local file in your project folder and restart the development server. Learn more: https://goo.gl/MMTaZt
[0]
```
---------------------------------------------
### Error log on http://127.0.0.1:3000/:
```
×
TypeError: Cannot read property 'invoke' of undefined
App.componentDidMount
D:/ds/src/App.js:16
  13 | 
  14 | componentDidMount() {
  15 | 	// when the component mounts, get the list of .wav files
> 16 | 	window.ipcRenderer.invoke('load-files')
     | ^  17 | 	.then(files => {
  18 | 		console.log('files', files);
  19 | 		this.setState({
View compiled
▶ 17 stack frames were collapsed.
Module../src/index.js
D:/ds/src/index.js:5
  2 | import ReactDOM from 'react-dom';
  3 | import App from './App';
  4 | 
> 5 | ReactDOM.render(<App/>, document.getElementById('root'));
View compiled
__webpack_require__
D:/ds/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
D:/ds/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://127.0.0.1:3000/static/js/main.chunk.js:134:18
__webpack_require__
D:/ds/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
checkDeferredModules
D:/ds/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
D:/ds/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://127.0.0.1:3000/static/js/main.chunk.js:1:91
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

**Comment by burgil** [comment]
![image](https://user-images.githubusercontent.com/41600149/128582191-01fc2aa2-1d2f-4be1-9396-27b9dc0e69c4.png)
![image](https://user-images.githubusercontent.com/41600149/128582195-4e7d20a5-b38f-41ed-b1f8-afeadb4b934a.png)
![image](https://user-images.githubusercontent.com/41600149/128582198-e5a4720b-d487-4662-a9d0-d9e02d1a18a8.png)
![image](https://user-images.githubusercontent.com/41600149/128582204-12278f5f-0635-412c-ad57-4d689cb8c1ca.png)
![image](https://user-images.githubusercontent.com/41600149/128582211-9b4f7260-4707-4e02-8438-f22602db7be2.png)
![image](https://user-images.githubusercontent.com/41600149/128582215-c76c540c-2241-40f9-8be5-eed7bb826599.png)
![image](https://user-images.githubusercontent.com/41600149/128582216-832410ac-e0c0-4f56-aad9-40e53f3e669a.png)

**Comment by burgil** [comment]
Javascript Popup Error Log on Electron:
```[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: bad "chunk id": expected "RIFF" or "RIFX", got "\u0000\u0005\u0016\u0007"
    at Reader._onRiffID (D:\ds\node_modules\wav\lib\reader.js:75:24)
    at process (D:\ds\node_modules\stream-parser\index.js:270:20)
    at D:\ds\node_modules\stream-parser\index.js:204:14
    at D:\ds\node_modules\stream-parser\index.js:294:16
    at Reader.transform [as _transform] (D:\ds\node_modules\stream-parser\index.js:176:3)
    at Reader.Transform._read (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Reader.Transform._write (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_writable.js:279:12)
    at writeOrBuffer (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_writable.js:266:5)
    at Reader.Writable.write (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_writable.js:211:11)

[OK]```

**Comment by BuenoRuben** [comment]
> Javascript Popup Error Log on Electron:
> 
> ```
> Error
> 
> [Main Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> Error: bad "chunk id": expected "RIFF" or "RIFX", got "\u0000\u0005\u0016\u0007"
>     at Reader._onRiffID (D:\ds\node_modules\wav\lib\reader.js:75:24)
>     at process (D:\ds\node_modules\stream-parser\index.js:270:20)
>     at D:\ds\node_modules\stream-parser\index.js:204:14
>     at D:\ds\node_modules\stream-parser\index.js:294:16
>     at Reader.transform [as _transform] (D:\ds\node_modules\stream-parser\index.js:176:3)
>     at Reader.Transform._read (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_transform.js:184:10)
>     at Reader.Transform._write (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_transform.js:172:12)
>     at doWrite (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_writable.js:279:12)
>     at writeOrBuffer (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_writable.js:266:5)
>     at Reader.Writable.write (D:\ds\node_modules\wav\node_modules\readable-stream\lib\_stream_writable.js:211:11)
> 
> [OK]```
> ```

did you managed to solve this?

**Comment by lissyx** [comment]
The error is explicit: `expected "RIFF" or "RIFX", got "\u0000\u0005\u0016\u0007"` you're passing wrong data to the model. It expects WAV, as documented.
