### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by ghost** [mozilla/DeepSpeech-examples#153]
While running I get the following error : 
`(deepspeech) C:\Users\jhiman\deepspeech\mic_vad_streaming>python mic_vad_streaming.py -m C:\Users\jhiman\Downloads\deepspeech-0.9.3-models.scorer -s C:\Users\jhiman\Downloads\deepspeech-0.9.3-models.pbmm
Initializing model...
INFO:root:ARGS.model: C:\Users\jhiman\Downloads\deepspeech-0.9.3-models.scorer
TensorFlow: v2.3.0-6-g23ad988fcd
DeepSpeech: v0.9.3-0-gf2e9c858
ERROR: Model provided has model identifier ' lm ', should be 'TFL3'

Error at reading model file C:\Users\jhiman\Downloads\deepspeech-0.9.3-models.scorer
Traceback (most recent call last):
  File "C:\Users\jhiman\deepspeech\mic_vad_streaming\mic_vad_streaming.py", line 224, in <module>
    main(ARGS)
  File "C:\Users\jhiman\deepspeech\mic_vad_streaming\mic_vad_streaming.py", line 163, in main
    model = deepspeech.Model(ARGS.model)
  File "C:\Users\jhiman\deepspeech\lib\site-packages\deepspeech\__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)
`

**Comment by TheDark** [comment]
Download and use the .tflite file instead of the .pbmm one:

`python mic_vad_streaming.py -m C:\Users\jhiman\Downloads\deepspeech-0.9.3-models.scorer -s C:\Users\jhiman\Downloads\deepspeech-0.9.3-models.tflite`
