### ISSUE TITLE
File "/home/me/DeepSpeech-examples/vad_transcriber/wavSplit.py", line 13, in read_wave  AssertionError   assert num_channels == 1 

### ISSUE THREAD

**Issue by shashi-netra** [mozilla/DeepSpeech-examples#27]
Hi, I am trying to run the `audioTranscript_cmd.py` example against a `wav` file and keep getting this error. Interestingly I am able to run the same file from `Deepspeech` command-line and get some results, albeit mostly noise. Any ideas on what's causing this?

```
python3 audioTranscript_cmd.py --aggressive 1 --audio ../audio-files/5192.wav --model ./models/
DEBUG:root:Transcribing audio file @ ../audio-files/5192.wav
DEBUG:root:Found Model: ./models/output_graph.pb
DEBUG:root:Found Language Model: ./models//lm.binary
DEBUG:root:Found Trie: ./models//trie
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2020-04-04 08:53:03.198130: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
DEBUG:root:Loaded model in 0.100s.
DEBUG:root:Loaded language model in 0.000s.
DEBUG:root:Loaded model sample rate: 16000Hz.

Filename                       Duration(s)          Inference Time(s)    Model Load Time(s)   LM Load Time(s)
DEBUG:root:Caught the wav file @: ../audio-files/5192.wav
Traceback (most recent call last):
  File "audioTranscript_cmd.py", line 97, in <module>
    main(sys.argv[1:])
  File "audioTranscript_cmd.py", line 51, in main
    model_sample_rate=model_retval[3])
  File "/home/me/DeepSpeech-examples/vad_transcriber/wavTranscriber.py", line 93, in vad_segment_generator
    audio, sample_rate, audio_length = wavSplit.read_wave(wavFile)
  File "/home/me/DeepSpeech-examples/vad_transcriber/wavSplit.py", line 13, in read_wave
    assert num_channels == 1
AssertionError

```

**Comment by lissyx** [comment]
Are you passing mono file? The assert check this, I'm sure you are passing stereo.

**Comment by shashi-netra** [comment]
thanks for responding.  Is the recommended way to use FFmpeg to convert stereo to mono? Or is there built-in functionality inside Deepspeech to achieve that?
