### ISSUE TITLE
[Nodejs] TypeError: modelStream.feedAudioContent is not a function

### ISSUE THREAD

**Issue by qixintechnology** [mozilla/DeepSpeech-examples#43]
**Hello! I met this issue when I run examples <nodejs_mic_vad_streaming> and <web_microphone_websocket>.

This issue happened when I started to speak, for both of above 2 examples.

I use the original code and didn't change anything.

Please help on this. Thanks!**

[Detail of the issue]:

-(node:31408) UnhandledPromiseRejectionWarning: TypeError: modelStream.feedAudioContent is not a function
    at feedAudioContent (/Users/ericyao/Desktop/DeepSpeech-examples/nodejs_mic_vad_streaming/start.js:193:14)
    at processSilence (/Users/ericyao/Desktop/DeepSpeech-examples/nodejs_mic_vad_streaming/start.js:97:3)
    at vad.processAudio.then (/Users/ericyao/Desktop/DeepSpeech-examples/nodejs_mic_vad_streaming/start.js:57:5)
(node:31408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by lissyx** [comment]
#33
