### ISSUE TITLE
TypeError: promisify is not a function in ffmpeg vad streaming test

### ISSUE THREAD

**Issue by Yuye-Castle** [mozilla/DeepSpeech-examples#6]
os: ubuntu16.04
nvidia gpu: geforce GTX 1060
nodejs version: v6.17.1
npm version: 3.10.10

I run the following command:
```
 node ./index.js --audio ../audio/2830-3980-0043.wav  --model ../model/output_graph.pbmm
then got the following error: 
/home/server/work/DeepSpeech/DeepSpeech-examples-r0.6/ffmpeg_vad_streaming/node_modules/util-promisifyall/index.js:23
        object[`${key}Async`] = promisify(func)
                                ^

TypeError: promisify is not a function
    at _promisifyAllFunctions (/home/server/work/DeepSpeech/DeepSpeech-examples-r0.6/ffmpeg_vad_streaming/node_modules/util-promisifyall/index.js:23:33)
    at module.exports (/home/server/work/DeepSpeech/DeepSpeech-examples-r0.6/ffmpeg_vad_streaming/node_modules/util-promisifyall/index.js:30:3)
    at Object.<anonymous> (/home/server/work/DeepSpeech/DeepSpeech-examples-r0.6/ffmpeg_vad_streaming/node_modules/node-vad/lib/vad.js:4:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
```
i think this is related with node version. 
do you have any good solution?

**Comment by lissyx** [comment]
> i think this is related with node version.
> do you have any good solution?

This is coming from dependencies of dependencies, it seems. NodeJS v6 is quite old already, I'm not sure how much it is worth trying to fix that (not to mention I don't understand the issue).

**Comment by lissyx** [comment]
@Yuye-Castle https://nodejs.org/api/util.html#util_util_promisify_original "added in v8.0.0"

**Comment by lissyx** [comment]
https://github.com/nodejs/Release v6 is End-of-Life since April. DeepSpeech still works with it, but obviously not this example. I'm sorry, but I don't think we're going to fix that.
