### ISSUE TITLE
Error: spawn sox ENOENT

### ISSUE THREAD

**Issue by puschmie** [mozilla/DeepSpeech-examples#97]
Hi, 
I'm running the deepspeech nodejs module on Ubuntu 18.04. Ubuntu is setup as a WSL2 virtual machine under Windows 10.
I was trying to get the nodejs_wav example to run but I keep running into the following error: 

`TensorFlow: v2.2.0-24-g1c1b2b9
DeepSpeech: v0.8.2-0-g02e4c76
2020-11-03 19:20:08.587514: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: spawn sox ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn sox',
  path: 'sox',
  spawnargs: [
    '--no-dither',
    '/tmp/4fe092db-b3a6-48bb-b00c-04452e396cc2',
    '--bits',
    16,
    '--rate',
    16000,
    '--channels',
    1,
    '--encoding',
    'signed-integer',
    '--endian',
    'little',
    '--compression',
    0,
    '--type',
    'raw',
    '-'
  ]
}`

I've looked around a bunch, but couldn't find a solution that works for me. I've manually added the sox folder to the $PATH variable, installed sox via brew and via npm, reinstalled nodejs several times at different versions, nothing works.. 

Any help is appreciated! 
Thanks in advance :)

**Comment by LKNSI** [comment]
> Install SoX. You can download it, or you can do apt-get install sox
